name: CoinsAPI
version: 1.3.1
author: DarkPhantom1337
description: CoinsAPI plugin for version 1.16.5
main: ua.darkphantom1337.coinsapi.Main
softdepend:
  - GadgetsMenu
  - LuckPerms
commands:
  money:
    aliases: [coins]
  level:
    aliases: [lvl]
  playedTime:
    aliases: [plTime]
  shop:
  fly:
  cspawn: